[jwt]
algorithm="HS256"
secret="secret"
expiresIn="10m"

[auth]
defaultUsers=[
]

[http]
port=44000
publicUrl="http://localhost:8080/auth"

[sql]
url="mysql://root:root@localhost:3306/auth_development"

[mqtt]
url="mqtt://localhost/"