[jwt]
algorithm="HS256"
secret="secret"


[auth]
defaultUsers=[
]

[http]
port=44000
publicUrl="http://localhost:44000/"

[mysql]
host="localhost"
user="root"
password="root"
database="auth_development"

[mqtt]
url="mqtt://localhost/"