[jwt]
algorithm="HS256"
secret="secret"


[auth]
defaultUsers=[
]

[http]
port=8080
publicUrl="http://localhost:8080/"

[mysql]
host="localhost"
user="root"
password="root"
database="auth_development"

[mqtt]
url="mqtt://localhost/"